Split visualizations into packs
silx-kit/h5web pull request #435
Opened 2021-01-21 14:56 UTC by axelboc

2021-01-21 16:13 UTC, axelboc reviewed
I feel like this was worthwhile:

- The NeXus visualization are now more clearly separate from the core visualization in the tree and decoupled from them in the code.
- Letting each pack check which of its visualizations are supported by a given entity is very flexible, and will allow us to more easily fetch entities from the store lazily if need be.
- Almost no duplication was introduced thanks to the sharing of `Visualizer` and the new `useActiveVis` custom hook. We've actually removed duplication by combining the two Nexus `supportsEntity` functions directly into the Nexus pack's `getSupportedVis` function.

2021-01-21 16:14 UTC, axelboc commented
You should probably pull the branch to get a better feel for the new structure. I'm not sure about the location of a couple of files, like `VisPackChooser`.

2021-01-22 09:05 UTC, loichuder requested changes
I would put `VisPackChooser` and `visualizer/hooks` at the root of `vis-packs`.

Also, it feels weird to have `models` files in a `shared` folder and one in the root of the pack folder. What about having the `shared` folder only contain components while other files (`models`, `utils` and `hooks`) are moved at the root of the pack folder ?

`Visualizer` name is no longer fitting in my opinion. It can stay like this for now but we should perhaps think about another name (we could revert to `VisDisplay` ?)

2021-01-22 09:35 UTC, axelboc commented on src/h5web/vis-packs/nexus/shared/utils.test.ts
> -  });
`isNxInterpretation` is no longer an exported utility -- it's used by the Nexus packs' `getSupportedVis` utility and is therefore tested by this utility's tests.

2021-01-22 09:37 UTC, axelboc commented on src/h5web/vis-packs/nexus/utils.test.ts
> +      expect(supportedVis).toEqual(NEXUS_VIS.image);
I'm just as surprise as you, but this is a valid way to access a value in a `Record` indexed by an enum. It autocompletes and everything!

2021-01-22 09:42 UTC, axelboc commented on src/h5web/visualizer/VisPackChooser.tsx
> +  return <CorePack entity={entity} />;
`VisPackChooser`? The logic is covered by the E2E specs. I don't think integration tests would add any value.

2021-01-22 09:54 UTC, axelboc commented
> I would put VisPackChooser and visualizer/hooks at the root of vis-packs.

Yeah, I wasn't sure because you could argue that the `Visualizer` itself is also a shared component of the two packs. Since we extracted it into its own root folder, I thought maybe the other things that were shared by the two packs had to go in the same folder, but no, they're different things, you're right. 👍 

> Also, it feels weird to have models files in a shared folder and one in the root of the pack folder. What about having the shared folder only contain components while other files (models, utils and hooks) are moved at the root of the pack folder ?

Yeah, the problem was differentiating the pack's utilities (`getSupportedVis`, `getDefaultPath`), from the visualization's utilities (which are numerous). Perhaps we could rename the files `pack-utils` and `vis-utils` (or keep the latter as `utils`)? 

> Visualizer name is no longer fitting in my opinion. It can stay like this for now but we should perhaps think about another name (we could revert to VisDisplay ?)

True. It's a shame that `vis-display` wouldn't be a great name for the folder...

2021-01-22 10:00 UTC, loichuder commented
> Yeah, the problem was differentiating the pack's utilities (`getSupportedVis`, `getDefaultPath`), from the visualization's utilities (which are numerous). Perhaps we could rename the files `pack-utils` and `vis-utils` (or keep the latter as `utils`)?

`pack-utils` and `utils` seems good to me.

2021-01-22 10:23 UTC, axelboc commented
Cool, moving the utility/model/hook files out of the `shared` folders really cleans things up. 💯 

- I was able to merge two `hooks` files in the core pack (`core/hooks` which contained `useDatasetValue/s` and `core/shared/hooks`).
- I moved the raw and scalar vis and their CSS files in sub-folders to match the other core visualisations.
- I moved the Spectrum vis toolbar config from `nexus/shared/config` to `nexus/spectrum/config`. It's the only file in the folder, but it matches the structure inside the core pack.

2021-01-22 10:36 UTC, loichuder approved these changes
Looks good to me !

2021-01-22 10:44 UTC, merged