Added support for complex in Matrix and ScalarVis
silx-kit/h5web pull request #507
Opened 2021-02-18 11:43 UTC by loichuder

First step of #310. I indeed plan to implement complex-specific visus after that.

I perhaps went a bit overboard with the amount of change in this one :sweat_smile: 

A digest:
- I used the same trick as in #499 as I added a new complex type in h5web. The fact that a dataset contains complex data is checked in the providers to convert the type appropriately to the new complex type.
- I removed the distinction between `HDF5BaseType` and `HDF5AdvancedType` as it was artificial. I instead added `DisplayableType` union that contains the types that can be displayed as strings (including the `HDF5ComplexType` now). I recycled the `HDF5BaseType` guards to check for this `DisplayableType` for the `MatrixVis` and `ScalarVis`.
-  I needed a unified way to represent complex numbers h5web. I could have stuck with strings but anticipating the complex-specific operations to come, I used [complex.js](https://www.npmjs.com/package/complex.js) to have a dedicated `Complex` type.

2021-02-19 08:33 UTC, loichuder commented
Waiting for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51305 to be published to fix the lint but happy to get your review in the meantime @axelboc

2021-02-19 09:48 UTC, axelboc requested changes

2021-02-19 09:48 UTC, axelboc commented on src/h5web/providers/jupyter/models.ts
> +export type JupyterComplexArray = JupyterComplex[];
Same, I don't think having `JupyterComplexArray` is required. `JupyterComplex[]` works just as well.

2021-02-19 09:48 UTC, axelboc commented on src/h5web/providers/models.ts
> +  : T extends HDF5StringType | HDF5ComplexType
I would rather see a separate logical branch that returns `Complex`. Here you're saying that the value is a `string`, which is wrong. `ScalarVis` and `MatrixVis` should explicitely accept `Complex` and `Complex[]` values.

2021-02-19 09:48 UTC, axelboc commented on src/h5web/providers/models.ts
> +export type ComplexArray = (ComplexArray | Complex)[];
With my comment above, I think this will type no longer be relevant. It should be achieved with type `Value` above.

2021-02-19 11:16 UTC, axelboc approved these changes

2021-02-22 07:32 UTC, loichuder commented
/approve

2021-02-22 08:02 UTC, merged