Simplify HDF5 types and separate out HDF5 from HSDS type classes
silx-kit/h5web pull request #592
Opened 2021-04-07 13:33 UTC by axelboc

I wasn't able to go as far as I'd planned by replacing the union of HDF5 types with `interface HDF5Type { class: HDF5TypeClass; }`. This led to some issues, notably when using `HDF5Type` as a return type of the provider's conversion functions. The significant benefit of a type union `A | B | C` is that TypeScript is able to infer the sub-types `A`, `B` and `C` inline, without the need for type guards.

So I've made only two changes:

1. I've merged a few HDF5 type interfaces together:
  - `HDF5FloatType` and `HDF5IntegerType` are now represented with a single `HDF5NumericType` interface.
  - Unsigned integers now have their own `HDF5TypeClass` entry and are also represented with `HDF5NumericType`.
  - `HDF5VLenType` is now represented by `HDF5ArrayType` (by making the latter's `dims` property optional).
2. I've completely separated out the HDF5 and HSDS type classes:
  - `HDF5TypeClass` now contains readable strings that we can render directly in the metadata viewer, like `integer`, 'boolean', etc.
  - `H5T_INTEGER` and the like, which are the classes returned by HSDS are no longer present anywhere outside of the HSDS provider code. This means we no longer have classes like `H5T_BOOL` that are never returned by HSDS.

2021-04-07 13:45 UTC, axelboc commented on src/h5web/metadata-viewer/utils.ts
> +    return `${type.class}, ${size}-bit${
`HDF5TypeClass.Unsigned` is `"unsigned integer"`, so we no longer need the extra ternary here.

2021-04-07 13:45 UTC, axelboc commented on src/h5web/providers/hsds/models.ts
>  }
I'll make some further simplifications here in my next PR.

2021-04-07 13:45 UTC, axelboc commented on src/h5web/providers/hsds/utils.ts
>  export function convertHsdsType(hsdsType: HsdsType): HDF5Type {
I've reorder the cases to match the `HsdsType` type union and extracted `convertHsdsCompoundType`

2021-04-08 08:02 UTC, loichuder requested changes
While this is taking the right direction, the resulting naming brings a lot of confusion.

`HDF5Type` are now further and further from the "real" types of the HDF5 spec. In fact, "separate out HDF5 from HSDS type classes" is a non-sense as it is HSDS that holds the "real" HDF5 types.

We must clearly signify in the naming that the interface `HDF5Type` is now a convenience type for h5web (as we did with `Shape`).

Also, I would have copied the (now old) `enum` of `HDF5TypeClass` into the HSDS part.

2021-04-08 08:36 UTC, axelboc commented
Renaming/moving the types is the end goal, but renaming before simplifying would just make everything more complicated. As I've done in past refactorings, I'll do all the renaming and moving at the end.

`HDF5TypeClass` is _no longer_ an HSDS enum. It will be unprefixed and moved to `models` in my final PR.

2021-04-08 08:38 UTC, loichuder commented
I see. Sorry for jumping the gun :sweat_smile:, go ahead and merge :+1:

2021-04-08 08:39 UTC, loichuder approved these changes

2021-04-08 09:00 UTC, merged